version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api_service
    networks:
      - sitwell-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  api_service:
    build:
      context: ./backend/api_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - inference_service
    networks:
      - sitwell-network
    environment:
      - INFERENCE_SERVICE_URL=http://inference_service:8001
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    restart: unless-stopped

  inference_service:
    build:
      context: ./backend/inference_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - sitwell-network
    volumes:
      - model-data:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  sitwell-network:
    driver: bridge

volumes:
  model-data: