services:
  api-service:
    build:
      context: ./backend/api-service
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api-service:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - INFERENCE_SERVICE_URL=http://inference-service:8001
    networks:
      - app-network

  inference-service:
    build:
      context: ./backend/inference-service
      dockerfile: Dockerfile
    container_name: inference-service
    ports:
      - "8001:8001"
    volumes:
      - ./backend/inference-service:/app
      - ./backend/inference-service/app/models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/yolov8n-pose.pt
      - INFERENCE_SERVICE_URL=http://inference-service:8001
    networks:
      - app-network

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
      - frontend-node-modules:/app/node_modules/.cache
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_INFERENCE_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
    depends_on:
      - api-service
      - inference-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-node-modules: